//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Entities
{
    using Models.Interfaces;
    using System;
    using System.Collections.Generic;
    
    public partial class Log :  Extensions.ExtensionLog, IEntityWithId
    {
        public System.Guid ID { get; set; }
        public Nullable<double> RxPower { get; set; }
        public Nullable<double> RxSensitivity { get; set; }
        public Nullable<double> TxPower { get; set; }
        public Nullable<double> TxSensitivity { get; set; }
        public Nullable<double> Temprature { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> CapturingDate { get; set; }
        public Nullable<System.Guid> AmplifierId { get; set; }
        public Nullable<System.Guid> SettingId { get; set; }
    
        public virtual Amplifier Amplifier { get; set; }
        public virtual GeneralSetting GeneralSetting { get; set; }
        public virtual User User { get; set; }
    }
}
